### ISSUE TITLE
VJ4Error

### ISSUE THREAD

**Issue by iceboy233** [vijos/jd4#12]
```
[I 170317 12:14:47 daemon:68] Submission: system, 1790, 58cb62b7d3d8a12d66e8f0c7
[I 170317 12:14:47 api:85] Getting problem data: system, 1790
[E 170317 12:14:48 daemon:52] 16
Traceback (most recent call last):
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 42, in handle
    await self.submission()
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 71, in submission
    with await cases_file_task as cases_file:
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 360, in __iter__
    return self.result()  # May raise too.
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/iceboy/git/jd4/jd4/cache.py", line 23, in cache_open
    await session.problem_data(domain_id, pid, file_path)
  File "/home/iceboy/git/jd4/jd4/api.py", line 95, in problem_data
    *error.get('args', []))
jd4.api.VJ4Error: 16
```

**Comment by twd2** [comment]
It seems like the websocket is available while api breaks.

**Comment by twd2** [comment]
Fixed by 81b818f8?

**Comment by iceboy233** [comment]
experimenting in `icebox`. seems no issue. 上海红茶馆 not updated yet.

**Comment by iceboy233** [comment]
上海红茶馆 updated
