### ISSUE TITLE
Not responding after connection broken

### ISSUE THREAD

**Issue by iceboy233** [vijos/jd4#16]
```
[W 170403 01:49:55 api:56] Connection lost with code 1006
[I 170403 01:49:55 daemon:171] Retrying after 30 seconds
[E 170403 01:55:25 daemon:170] 
Traceback (most recent call last):
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 163, in daemon
    await session.login_if_needed(config['uname'], config['password'])
  File "/home/iceboy/git/jd4/jd4/api.py", line 67, in login_if_needed
    await self.judge_noop()
  File "/home/iceboy/git/jd4/jd4/api.py", line 59, in judge_noop
    await self.get_json('judge/noop')
  File "/home/iceboy/git/jd4/jd4/api.py", line 40, in get_json
    params=kwargs) as response:
  File "/home/iceboy/.pyvenv/lib/python3.5/site-packages/aiohttp/client.py", lin
e 587, in __aenter__
    self._resp = yield from self._coro
  File "/home/iceboy/.pyvenv/lib/python3.5/site-packages/aiohttp/client.py", lin
e 274, in _request
    break
  File "/home/iceboy/.pyvenv/lib/python3.5/site-packages/aiohttp/helpers.py", li
ne 765, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
[I 170403 01:55:25 daemon:171] Retrying after 30 seconds
```

```
[E 170403 02:24:38 daemon:170] invalid content type text/html
Traceback (most recent call last):
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 163, in daemon
    await session.login_if_needed(config['uname'], config['password'])
  File "/home/iceboy/git/jd4/jd4/api.py", line 67, in login_if_needed
    await self.judge_noop()
  File "/home/iceboy/git/jd4/jd4/api.py", line 59, in judge_noop
    await self.get_json('judge/noop')
  File "/home/iceboy/git/jd4/jd4/api.py", line 41, in get_json
    return await json_response_to_dict(response)
  File "/home/iceboy/git/jd4/jd4/api.py", line 19, in json_response_to_dict
    raise Exception('invalid content type ' + response.content_type)
Exception: invalid content type text/html
[I 170403 02:24:38 daemon:171] Retrying after 30 seconds
```

**Comment by iceboy233** [comment]
Obsolete
