### ISSUE TITLE
BrokenPipeError

### ISSUE THREAD

**Issue by iceboy233** [vijos/jd4#3]
```
[E 170312 20:20:17 daemon:54] [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 44, in handle
    await self.submission()
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 72, in submission
    await self.judge(cases_file, package)
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 105, in judge
    status, score, time_usage_ns, memory_usage_bytes, stderr = await case.judge(sandbox, package)
  File "/home/iceboy/git/jd4/jd4/case.py", line 91, in judge
    cgroup_file='/in/cgroup'))
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 290, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/iceboy/git/jd4/jd4/case.py", line 121, in do_stdin
    copyfileobj(src, dst, CHUNK_SIZE)
  File "/usr/local/lib/python3.5/shutil.py", line 76, in copyfileobj
    fdst.write(buf)
BrokenPipeError: [Errno 32] Broken pipe
```

This might because the user program exited before reading all input. We should ignore this error.

**Comment by iceboy233** [comment]
reference submission: `58c52946d3d8a16c62a24436`
