### ISSUE TITLE
hang

### ISSUE THREAD

**Issue by iceboy233** [vijos/jd4#35]
stack trace:

```
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    "__main__", mod_spec)
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 11, in <module>
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 102, in <module>
    exec(code, run_globals)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 11, in <module>
    exec(code, run_globals)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 11, in <module>
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    exec(code, run_globals)
    exec(code, run_globals)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 11, in <module>
    exec(code, run_globals)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 11, in <module>
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 102, in <module>
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 11, in <module>
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 102, in <module>
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 102, in <module>
      self.run_forever()
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 102, in <module>
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
Traceback (most recent call last):
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 102, in <module>
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    "__main__", mod_spec)
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
    exec(code, run_globals)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 11, in <module>
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 11, in <module>
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 102, in <module>
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 102, in <module>
    self._callback(*self._args)
    self._run_once()
    self._run_once()
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    result = coro.send(None)
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 60, in _init
    "__main__", mod_spec)
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 98, in create_sandboxes
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
    exec(code, run_globals)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 11, in <module>
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 68, in _handle_child
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 102, in <module>
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    result = coro.send(None)
    self.run_forever()
    self.run_forever()
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 60, in _init
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    result = coro.send(None)
    result = coro.send(None)
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 60, in _init
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 60, in _init
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 98, in create_sandboxes
    return self._sock.recv_into(b)
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 98, in create_sandboxes
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 98, in create_sandboxes
KeyboardInterrupt
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 61, in _handle_child
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 68, in _handle_child
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 68, in _handle_child
KeyboardInterrupt
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    self._run_once()
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
    return self._sock.recv_into(b)
    return self._sock.recv_into(b)
KeyboardInterrupt
    self._run_once()
KeyboardInterrupt
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 60, in _init
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 98, in create_sandboxes
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 68, in _handle_child
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
    handle._run()
    handle._run()
    handle._run()
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 11, in <module>
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 102, in <module>
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    return self._sock.recv_into(b)
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    self._callback(*self._args)
KeyboardInterrupt
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    result = coro.send(None)
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 60, in _init
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
    result = coro.send(None)
    self._run_once()
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 98, in create_sandboxes
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 60, in _init
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 68, in _handle_child
    result = coro.send(None)
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 60, in _init
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 98, in create_sandboxes
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 98, in create_sandboxes
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 68, in _handle_child
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 60, in _init
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 61, in _handle_child
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    return self._sock.recv_into(b)
KeyboardInterrupt
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
    exec(code, run_globals)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 11, in <module>
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 102, in <module>
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    return self._sock.recv_into(b)
    result = coro.send(None)
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 60, in _init
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 98, in create_sandboxes
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 61, in _handle_child
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
KeyboardInterrupt
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 60, in _init
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 98, in create_sandboxes
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 61, in _handle_child
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 11, in <module>
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 102, in <module>
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 60, in _init
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 98, in create_sandboxes
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 61, in _handle_child
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 11, in <module>
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 102, in <module>
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 60, in _init
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 98, in create_sandboxes
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 61, in _handle_child
KeyboardInterrupt
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 98, in create_sandboxes
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 68, in _handle_child
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    return self._sock.recv_into(b)
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 11, in <module>
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 102, in <module>
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
    exec(code, run_globals)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 11, in <module>
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 102, in <module>
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
    handle._run()
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 11, in <module>
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 102, in <module>
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 60, in _init
    handle._run()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1424, in _run_once
    handle._run()
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 98, in create_sandboxes
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 61, in _handle_child
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
KeyboardInterrupt
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 60, in _init
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 98, in create_sandboxes
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 68, in _handle_child
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 60, in _init
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 98, in create_sandboxes
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 61, in _handle_child
    return self._sock.recv_into(b)
KeyboardInterrupt
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 175, in <module>
    get_event_loop().run_until_complete(daemon())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1388, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
KeyboardInterrupt
```

**Comment by iceboy233** [comment]
last record `59119546d3d8a1646743bb54`
next record `59119cb2d3d8a1646743bb55`

**Comment by iceboy233** [comment]
Obsolete
