### ISSUE TITLE
CGroup file not found

### ISSUE THREAD

**Issue by iceboy233** [vijos/jd4#4]
```
[E 170312 20:25:41 base_events:1090] Task exception was never retrieved
future: <Task finished coro=<accept_and_limit.<locals>.limit_task() done, defined at /home/iceboy/git/j
d4/jd4/case.py:42> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/home/iceboy/git/jd4/jd4/case.py", line 45, in limit_task
    time_remain_ns = time_limit_ns - max(cgroup.cpu_usage_ns, idle_usage_ns())
  File "/home/iceboy/git/jd4/jd4/cgroup.py", line 85, in cpu_usage_ns
    return int(read_text_file(path.join(self.cpuacct_cgroup_dir, 'cpuacct.usage')))
  File "/home/iceboy/git/jd4/jd4/util.py", line 5, in read_text_file
    with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/fs/cgroup/cpuacct/jd4/_8g06b6j/cpuacct.us
age'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/iceboy/git/jd4/jd4/case.py", line 54, in limit_task
    while cgroup.kill():
  File "/home/iceboy/git/jd4/jd4/cgroup.py", line 72, in kill
    procs = self.procs
  File "/home/iceboy/git/jd4/jd4/cgroup.py", line 67, in procs
    map(int, read_text_file(path.join(self.cpuacct_cgroup_dir, 'cgroup.procs')).splitlines()),
  File "/home/iceboy/git/jd4/jd4/util.py", line 5, in read_text_file
    with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/fs/cgroup/cpuacct/jd4/_8g06b6j/cgroup.pro
cs'
```

**Comment by iceboy233** [comment]
Not seen for a while. Closing.
