### ISSUE TITLE
How to make jd4 talk with a unix socket file?

### ISSUE THREAD

**Issue by moetayuko** [vijos/jd4#49]
I started vj4 with
```bash
python3 -m vj4.server --listen=unix:/dev/shm/vj4.sock
```
and jd4 with
```bash
docker run --privileged --name jd4 \
     -v /opt/jd4/config/config.yaml:/root/.config/jd4/config.yaml \
     -v /opt/jd4/cache:/root/.cache/jd4 \
     -v /dev/shm/vj4.sock:/dev/shm/vj4.sock \
     vijos/jd4
```
nginx listens on port 80 and redirects to /dev/shm/vj4.sock

http service works well but if I set
```
server_url: http://172.17.0.1:80/
```
jd4 will report error:
```
[E 171005 03:58:05 daemon:171] 400, message='Invalid response status'
Traceback (most recent call last):
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 169, in daemon
    await gather(*done)
  File "/usr/lib/python3.5/asyncio/futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 310, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 150, in do_judge
    await session.judge_consume(JudgeHandler)
  File "/venv/lib/python3.5/site-packages/jd4/api.py", line 51, in judge_consume
    async with self.ws_connect(self.full_url('judge/consume-conn/websocket')) as ws:
  File "/venv/lib/python3.5/site-packages/aiohttp/client.py", line 603, in __aenter__
    self._resp = yield from self._coro
  File "/venv/lib/python3.5/site-packages/aiohttp/client.py", line 400, in _ws_connect
    headers=resp.headers)
aiohttp.client_exceptions.WSServerHandshakeError: 400, message='Invalid response status'
```

I guess jd4 needs to listen on the sock file directly, but how could I set config.yaml?

Thanks in advance!

**Comment by twd2** [comment]
It seems that the nginx is not well-configured and can not forward websocket requests.

**Comment by moetayuko** [comment]
Following instructions on https://www.nginx.com/blog/websocket-nginx/ and it works now, thanks a lot!
