### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by qwganker** [vijos/jd4#66]
[E 180626 15:42:39 web_protocol:356] Error handling request
Traceback (most recent call last):
  File "/home/wqiu/.local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 416, in start
    resp = yield from self._request_handler(request)
  File "/home/wqiu/.local/lib/python3.6/site-packages/aiohttp/web.py", line 325, in _handle
    resp = yield from handler(request)
  File "/home/wqiu/.local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 93, in impl
    return (yield from handler(request))
  File "/home/wqiu/.local/lib/python3.6/site-packages/sockjs/route.py", line 161, in websocket
    session = self.manager.get(sid, True, request=request)
  File "/home/wqiu/work/cqrd/codecampus/vj4/vj4/app.py", line 110, in get
    timeout=self.timeout, loop=self.loop, debug=self.debug))
  File "/home/wqiu/work/cqrd/codecampus/vj4/vj4/handler/base.py", line 338, in __init__
    super(Connection, self).__init__(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'request'

**Comment by qwganker** [comment]
My linux kernel  version is 4.15.0-20-generic

**Comment by twd2** [comment]
Solved by https://github.com/vijos/vj4/issues/427
