### ISSUE TITLE
Parallel bugs

### ISSUE THREAD

**Issue by iceboy233** [vijos/jd4#7]
Between 61da7a360614cbe18e2ef2acfb13ed818f42d4f1 and da7ca3442a4418fb7db9d505ed512020e4cfcdf9.

```
Traceback (most recent call last):
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 42, in handle
    await self.submission()
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 70, in submission
    await self.judge(cases_file, package)
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 119, in judge
    status, score, time_usage_ns, memory_usage_bytes, stderr = await judge_task
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 290, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 111, in pool_judge
    return await case.judge(sandbox, package)
  File "/home/iceboy/git/jd4/jd4/case.py", line 72, in judge
    self.process_limit))
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 290, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/iceboy/git/jd4/jd4/cgroup.py", line 135, in wait_cgroup
    await sleep(.001)
TypeError: object NoneType can't be used in 'await' expression

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 111, in pool_judge
    return await case.judge(sandbox, package)
  File "/home/iceboy/git/jd4/jd4/case.py", line 72, in judge
    self.process_limit))
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 290, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/iceboy/git/jd4/jd4/case.py", line 98, in do_stdin
    with self.open_input() as src, open(stdin_file, 'wb') as dst:
  File "/usr/local/lib/python3.5/zipfile.py", line 1261, in open
    fheader = zef_file.read(sizeFileHeader)
  File "/usr/local/lib/python3.5/zipfile.py", line 662, in read
    self._file.seek(self._pos)
ValueError: seek of closed file

Task exception was never retrieved
future: <Task finished coro=<JudgeHandler.judge.<locals>.pool_judge() done, defined at /home/iceboy/git/jd4/jd4/daemon.py:108> exception=ValueError('seek of closed file',)>

Traceback (most recent call last):
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 42, in handle
    await self.submission()
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 68, in submission
    cases_file, package = await gather(cache_open(self.session, domain_id, pid), self.build())
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 290, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 90, in build
    package, message = await build_fn(sandbox, self.request.pop('code').encode())
  File "/home/iceboy/git/jd4/jd4/langs.py", line 22, in _compiler_build
    read_pipe(output_file, _MAX_OUTPUT))
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 290, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/iceboy/git/jd4/jd4/compile.py", line 84, in build
    status = await sandbox.marshal(lambda: self.do_build(
  File "/home/iceboy/git/jd4/jd4/sandbox.py", line 62, in marshal
    length, = unpack('I', await self.reader.read(4))
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 482, in read
    yield from self._wait_for_data('read')
  File "/usr/local/lib/python3.5/asyncio/streams.py", line 419, in _wait_for_data
    'already waiting for incoming data' % func_name)
RuntimeError: read() called while another coroutine is already waiting for incoming data
```

**Comment by iceboy233** [comment]
Currently the `sandbox.marshal()` is not cancellable. Causing error "read() called while another coroutine is already waiting for incoming data".
