### ISSUE TITLE
[Error] BrokenPipeError(32, 'Broken pipe') On website

### ISSUE THREAD

**Issue by Philogag** [vijos/jd4#77]
### Env:
+ Centos 7
+ Docker version 19.03.2, build 6a30dfc
+ jd4 build by default Dockerfile
+ vj4 build by default Dockerfile
+ judge user set by default
#### docker-compuse.yml:
```
version: '3'
services:
    web:
        #build: .
        image: philogag/vj4:office
        restart: always
        command: vj4.server
        env_file: .env
        volumes:
            - "./data/run:/var/run/vj4"
        links:
            - mongodb
            - rabbitmq
        ports: [ "8888:8888" ]
        depends_on:
            - rabbitmq
            - mongodb

    # Before uncomment these lines, you should have created necessary files
    # like config.yaml for it.
    # See README.md for instructions.
    #-------------------------------------------------------------------------------
    judge:
        restart: always
        privileged: true
        #image: vijos/jd4
        image: philogag/jd4:office
        #command: bash -c "source /venv/bin/activate && \ python3 -m jd4.daemon"
        volumes:
            - "./data/judge/config.yaml:/root/.config/jd4/config.yaml"
            - "./data/judge/cache:/root/.cache/jd4"
            - "./data/judge/langs.yaml:/root/.config/jd4/langs.yaml"
        links:
            - web
            # - web_backend # uncomment this only if you have this service
        depends_on:
            - web
```
### Jd4 log:
+ **when start docker**
```
[D 190923 09:18:38 selector_events:65] Using selector: EpollSelector
[I 190923 09:18:38 pool:22] Using parallelism: 2
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 6, in <module>
    from jd4.case import read_cases
  File "/venv/lib/python3.5/site-packages/jd4/case.py", line 15, in <module>
    from jd4.compile import build
  File "/venv/lib/python3.5/site-packages/jd4/compile.py", line 13, in <module>
    from jd4.pool import get_sandbox, put_sandbox
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 29, in <module>
    _init()
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 23, in _init
    sandboxes_task = create_sandboxes(parallelism)
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 161, in create_sandboxes
    _handle_child(child_socket, root_dir, in_dir, out_dir)
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 120, in _handle_child
    create_namespace()
  File "jd4/_sandbox.pyx", line 35, in jd4._sandbox.create_namespace
  File "/venv/lib/python3.5/site-packages/jd4/util.py", line 44, in write_text_file
    f.write(text)
PermissionError: [Errno 1] Operation not permitted
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 6, in <module>
    from jd4.case import read_cases
  File "/venv/lib/python3.5/site-packages/jd4/case.py", line 15, in <module>
    from jd4.compile import build
  File "/venv/lib/python3.5/site-packages/jd4/compile.py", line 13, in <module>
    from jd4.pool import get_sandbox, put_sandbox
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 29, in <module>
    _init()
  File "/venv/lib/python3.5/site-packages/jd4/pool.py", line 23, in _init
    sandboxes_task = create_sandboxes(parallelism)
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 161, in create_sandboxes
    _handle_child(child_socket, root_dir, in_dir, out_dir)
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 120, in _handle_child
    create_namespace()
  File "jd4/_sandbox.pyx", line 35, in jd4._sandbox.create_namespace
  File "/venv/lib/python3.5/site-packages/jd4/util.py", line 44, in write_text_file
    f.write(text)
PermissionError: [Errno 1] Operation not permitted
[I 190923 09:18:38 cgroup:29] Initializing cgroup: /sys/fs/cgroup/cpuacct/jd4, /sys/fs/cgroup/memory/jd4, /sys/fs/cgroup/pids/jd4
[I 190923 09:18:38 api:88] Login
[I 190923 09:18:38 daemon:133] Update problem data
[D 190923 09:18:38 daemon:137] Invalidated system/1000
[I 190923 09:18:38 api:59] Connected
```

+ **when submit code**
```
[I 190923 09:18:38 daemon:70] Submission: system, 1000, 5d831827fd777a00018ab9de
[I 190923 09:18:38 api:107] Getting problem data: system, 1000
[E 190923 09:18:38 daemon:57] unpack requires a bytes object of length 4
Traceback (most recent call last):
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 47, in do_record
    await self.do_submission()
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 72, in do_submission
    package = await self.build()
  File "/venv/lib/python3.5/site-packages/jd4/daemon.py", line 86, in build
    package, message, _, _ = await shield(build(self.lang, self.code.encode()))
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/venv/lib/python3.5/site-packages/jd4/compile.py", line 153, in build
    return await build_fn(code)
  File "/venv/lib/python3.5/site-packages/jd4/compile.py", line 122, in _compiler_build
    await compiler.prepare(sandbox, code)
  File "/venv/lib/python3.5/site-packages/jd4/compile.py", line 79, in prepare
    await sandbox.reset()
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 43, in reset
    self.call(SANDBOX_RESET_CHILD))
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/venv/lib/python3.5/site-packages/jd4/sandbox.py", line 47, in call
    length, = unpack('I', await self.reader.read(4))
struct.error: unpack requires a bytes object of length 4
```

**Comment by undefined-moe** [comment]
linux core 4.4+ required for jd4

**Comment by chiyang10000** [comment]
I think `echo 640 > /proc/sys/user/max_user_namespaces`  on the host machine with `CentOS 7` would help.

When checking `cat /proc/sys/user/max_user_namespaces`, it used to be 0. After modifying the kernel value, `unshare -U bash` outputs `whoami: cannot find name for user ID 65534` rather than `unshare: unshare failed: Invalid argument`.

It also applies https://github.com/vijos/jd4/issues/63.

Referring to https://unix.stackexchange.com/questions/479635/unable-to-create-user-namespace-in-rhel
