### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by iceboy233** [vijos/jd4#8]
```
Traceback (most recent call last):
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 44, in handle
    await self.submission()
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 72, in submission
    await self.judge(cases_file, package)
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 105, in judge
    status, score, time_usage_ns, memory_usage_bytes, stderr = await case.judge(
sandbox, package)
  File "/home/iceboy/git/jd4/jd4/case.py", line 62, in judge
    self.process_limit))
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 290, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
concurrent.futures._base.CancelledError
```

```
Exception ignored in: 'jd4._compare.StreamReader.read'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/zipfile.py", line 844, in read
    data = self._read1(n)
  File "/usr/local/lib/python3.5/zipfile.py", line 912, in _read1
[E 170315 10:50:44 daemon:54] [Errno 2] No such file or directory: 'foo'
Traceback (most recent call last):
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 44, in handle
    await self.submission()
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 72, in submission
    await self.judge(cases_file, package)
  File "/home/iceboy/git/jd4/jd4/daemon.py", line 105, in judge
    status, score, time_usage_ns, memory_usage_bytes, stderr = await case.judge(
sandbox, package)
  File "/home/iceboy/git/jd4/jd4/case.py", line 62, in judge
    self.process_limit))
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 290, in _wakeup
    future.result()
  File "/usr/local/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/iceboy/git/jd4/jd4/compile.py", line 32, in execute
    return await sandbox.marshal(lambda: self.do_execute(
  File "/home/iceboy/git/jd4/jd4/sandbox.py", line 65, in marshal
    raise err
FileNotFoundError: [Errno 2] No such file or directory: 'foo'
    data += self._read2(n - len(data))
  File "/usr/local/lib/python3.5/zipfile.py", line 944, in _read2
    data = self._fileobj.read(n)
  File "/usr/local/lib/python3.5/zipfile.py", line 662, in read
    self._file.seek(self._pos)
ValueError: seek of closed file
```

**Comment by iceboy233** [comment]
fixed by 56d2e149f862a529c618bd81bcbacd84901b3270 and 46fdbd2a8567019849c738940c96c88b4f8380d8
